version: "3.7"

services:
  db:
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: fontys
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
  api:
    depends_on: ["db"]
    image: fontys-api
    restart: always
    build:
      context: ./services/api
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=ROOT
      - DB_NAME=fontys
  ui:
    depends_on: ["api"]
    image: fontys-ui
    restart: always
    build:
      context: ./services/ui
    ports:
      - "8080:80"
volumes:
  db-data: